### ISSUE TITLE
Multiple feature requests

### ISSUE THREAD

**Issue by HardNekkig** [sjaakbanaan/untappd-data-visualised#1]
Want to:

- Be able to see the checkin location on the map plots
- Next to the top10 global ratings i want to see my own rating
- When selecting a country, keep the entire list but highlight the selected option
- Top 10 most checked in beers
- When clicking a beer in the top 10 i want to go to the checkin and not the beer
- Add pie charts and top combo overview for flavor profiles
- Line graph alcohol percentage & bitterness
- Bar chart for some of the stats (alcohol, ibu, flavors)
- (Optional) Filter on beer profile to see best rated profiles, with multi select
- (Optional) Word cloud with flavors in a specific beer profile range

**Comment by sjaakbanaan** [comment]
Thanks for the suggestions, I'll keep track of progress here:

Want to:

~~- Be able to see the checkin location on the map plots~~
- Next to the top10 global ratings i want to see my own rating
- When selecting a country, keep the entire list but highlight the selected option
~~- Top 10 most checked in beers~~
~~- When clicking a beer in the top 10 i want to go to the checkin and not the beer~~
- Add pie charts and top combo overview for flavor profiles
- Line graph alcohol percentage & bitterness
- Bar chart for some of the stats (alcohol, ibu, flavors)
- (Optional) Filter on beer profile to see best rated profiles, with multi select
- (Optional) Word cloud with flavors in a specific beer profile range

**Comment by sjaakbanaan** [comment]
Closing this one for now, i'll add the nice to haves to a different list.
