### ISSUE TITLE
Filter by Style

### ISSUE THREAD

**Issue by mk19807** [sjaakbanaan/untappd-data-visualised#4]
De titel zegt het al. Een extra filter plaatsen naast de huidige drie. En in het drop down menu ook wellicht cursief de stijlen die je nog niet hebt gedronken

**Comment by sjaakbanaan** [comment]
Good suggestion @mk19807, this filter option has been added. For now non checked-in styles are not included since this list is not available in beers.json. To get this, please do: `git pull` and after that `npm run start` again.
