### ISSUE TITLE
Bug in Frequency Stat Bar

### ISSUE THREAD

**Issue by mk19807** [sjaakbanaan/untappd-data-visualised#5]
De lijst van bier per jaar in de frequency bar stat is messed up als je maar 1 jaar hebt geselecteerd

De ABV staat op volgorde, maar niet de juiste.

Ik zou de IBU achterwege laten. Veel brouwers zetten die er niet bij in Untappd en het staat ook niet op het etiket

**Comment by sjaakbanaan** [comment]
- [ ] De lijst van bier per jaar in de frequency bar stat is messed up als je maar 1 jaar hebt geselecteerd
- [ ] De ABV staat op volgorde, maar niet de juiste.
- [ ] Ik zou de IBU achterwege laten. Veel brouwers zetten die er niet bij in Untappd en het staat ook niet op het etiket
